### ISSUE TITLE
Add metrics instrumentation to Morty controller

### ISSUE THREAD

**Issue by thomasgouveia** [morty-faas/morty#12]
Our project is growing in complexity and we're adding new features and functionality on a regular basis. As a result, it's becoming more difficult to keep track of how our platform is performing in production. In order to build a more and more performant platform, we need to be able to identify bottlenecks in our code.

This is why we should consider adding metrics instrumentation in our codebase. This will allow us to collect data on key performance metrics, such as response times, error rates, and throughput. We can then use this data to identify performance bottlenecks and proactively address them before they become major issues.

For the implementation, as we will also add traces in the future, I propose to use [Prometheus](https://prometheus.io/docs/guides/go-application/). It is simple to use, and it doesn't add a lot of complexity to our code. Metrics will be available on a specific port of the application, for example `http://localhost:8090/metrics`, in the [Prometheus](https://prometheus.io/) format.

Below a non-exhaustive list of what metrics we could add to begin :

**Controller**:
- Total number of function invocations 
- Total number of invocation for a given function
- Time (in ms) of a function invocation

**Comment by AlexandreBrg** [comment]
@thomasgouveia We should discriminate function invocation time depending if it's a cold or warm start of function
